import localFont from 'next/font/local';
import { Inter as FontSans } from 'next/font/google';
import '@/styles/globals.css';
import { cn } from '@lib/utils';

// const fontSans = FontSans({
//   subsets: ['latin'],
//   variable: '--font-sans',
// });

const fontSans = localFont({
  src: '../assets/fonts/SF-Pro.ttf',
  variable: '--font-sans',
});

const fontHeading = localFont({
  src: '../assets/fonts/SF-Pro.ttf',
  variable: '--font-heading',
});

export const metadata = {
  title: 'Ultimate Goals App',
  description: 'Generated by Jackson',
};

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body
        className={cn(
          'min-h-screen bg-background font-sans antialiased',
          fontSans.variable,
          fontHeading.variable
        )}
      >
        {children}
      </body>
    </html>
  );
}
